### ISSUE TITLE
Criar teste automatizados baseados nos conteúdos dos tutoriais

### ISSUE THREAD

**Issue by AndyFernandes** [InsightLab/PyMove#16]
Tomar como base os testes do [scikit-learn](https://github.com/scikit-learn/scikit-learn/tree/master/sklearn/tests) 

- [x] core
  - [x] dataframe
  - [x] grid
- [x] models
- [x] preprocessing
  - [x] compression
  - [x] filters
  - [x] segmentation
  - [x] stay_point_detection
- [x] semantic
- [x] utils
- [x] visualization

**Comment by regispires** [comment]
Ver também como é feito no Pandas e Dask.
