### ISSUE TITLE
Turn off prints

### ISSUE THREAD

**Issue by JoaoCarabetta** [InsightLab/PyMove#177]
**Is your feature request related to a problem? Please describe.**
There is too much printing. I rather have an API that does not print as much. For instance, if I want to use it on another project, I want it to run silently.

I'd recommend setting the verbosity to False by default.

**Describe the solution you'd like**
To have a way to control the verbosity of the logging. Maybe a global parameter that I toggle, ex:  `pymove.params.verbose=True/False`, which controls the printing. 

**Describe alternatives you've considered**

**Comment by flych3r** [comment]
please see #178
