### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by AndyFernandes** [InsightLab/PyMove#18]
- [x] Ajeitar o negocio do resources que tá comentado (solução aqui https://stackoverflow.com/questions/938733/total-memory-used-by-python-process)
- [x] Revisar docs das funções
- [x] Botar pra sempre retornar um objeto do tipo MoveDataFrame -> O que tá acontecendo: tenho um move dataframe, quando ponho uma operação `.loc`, `.iloc`, `at` ele retorna um dataframe
- [x] Melhorar exibição de legendas no folium
- [x] Validar colunas ao gerar dataframe.
```python
>>> list_data = [
             [39.984094, 116.319236, '2008-10-23 05:53:05', 1],
             [39.984198, 116.319322, '2008-10-23 05:53:06', 1],
             [39.984224, 116.319402, '2008-10-23 05:53:11', 1],
             [39.984224, 116.319402, '2008-10-23 05:53:11', 1],
             [39.984224, 116.319402, '2008-10-23 05:53:11', 1],
             [39.984224, 116.319402, '2008-10-23 05:53:11', 1]
]
>>> move_df = pymove.PandasMoveDataFrame(data=list_data, latitude="lat", longitude="lon", datetime="datetime", traj_id="id")
>>> print(move_df.dtypes)
lat         float64
lon         float64
datetime     object
id            int64
dtype: object
```
- [x] Tratar caso de dataframe sem as colunas do tipo especificado em `plot_all_features`
- [x] Exibir versão correta do pymove instalado através do `pip`
```python
>>> import pymove
>>> pymove.__version__
'0+unknown'
```
- [x] Corrigir erro ao ler dataframe usando `pm.read_csv` com coluna de data com nome não padrão
```python
df = pd.read_csv(filename, sep=sep, encoding=encoding, parse_dates=["datetime"])
```
- [x] Permitir a leitura de arquivos sem header utilizando `pymove.read_csv(filename)`
- [x] Erro ao instalar no windows devido ao README.md
`“path_to_your_anaconda_location/anaconda/envs/yourenvname”`
- [x] Erro ao importar o pymove no windows devido aos módulos `pwd` e `resource`
- [x] Rever funções em `pymove.utils.datetime`
    - slot_of_day_to_time
    - slot_of_day
    - slot
    - str_to_min_slot
- [x] Ao plotar multiplas trajetória no foliim, é exibido apenas um marcador de início e fim
- [x] Modificar os marcadores de início e fim de trajetória para ficarem mais legíveis

**Comment by flych3r** [comment]
O que fazer ao tentar remover colunas necessárias ao MoveDataFrame (LATITUDE, LONGITUTE, DATETIME) -> Os métodos `dropna`, `drop`, `set_index`, `astype` podem modificar estas colunas

Como o `_data` é que guarda o dataframe, como retornar nos métodos `at`, `loc` e `iloc` de modo que possa alterar os valores do dataframe usando essas se retornarem MoveDataFrame

**Comment by flych3r** [comment]
> Como o `_data` é que guarda o dataframe, como retornar nos métodos `at`, `loc` e `iloc` de modo que possa alterar os valores do dataframe usando essas se retornarem MoveDataFrame

É possível utilizar `getters` e `setters` de `@property` para que se comporte diferente nessas situações.
O problema agora é quando vai ser forçado o retorno como MoveDataFrame. Com o `at` e `loc` permite acessar apenas determinadas colunas de linhas específicas
