### ISSUE TITLE
Script pra atualizar versão PyMove no pip

### ISSUE THREAD

**Issue by AndyFernandes** [InsightLab/PyMove#19]
- https://dzone.com/articles/executable-package-pip-install
- Esse parece ser mais completinho: https://medium.com/@joel.barmettler/how-to-upload-your-python-package-to-pypi-65edc5fe9c56
- MAIS DO MAIS completo: https://realpython.com/pypi-publish-python-package/ 
- https://github.com/bast/pypi-howto

- https://stackoverflow.com/questions/32204769/pypi-is-it-possible-to-set-up-git-to-auto-update-my-package-on-pypi
- https://sherif.io/2016/09/30/Python-package-with-GitHub-PyPI.html
- https://pypi.org/project/auto-pypi/
- PRA UPLOAD: https://stackoverflow.com/questions/52700692/a-guide-for-updating-packages-on-pypi
- https://www.freecodecamp.org/news/how-to-use-github-as-a-pypi-server-1c3b0d07db2/

**Comment by ArinaSanches** [comment]
https://pypi.org/project/travis-pypi-integration/ integração com travis
