### ISSUE TITLE
Ajustes nas funções de core.dataframe

### ISSUE THREAD

**Issue by flych3r** [InsightLab/PyMove#26]
Sugestões de alterações dos locais das funções, parâmetros e padronização de semelhantes

- [x] generate_day_of_the_week, generate_time_of_day => padronizar os nomes das colunas para caixa baixa ou capitalizados

- [x] generate_time_of_day => trecho do print está mal formatado

- [x] generate_datetime_in_format_cyclical => não esta perto de outros geradores de features que usam datetime

- [x] generate_weekend_features => 
  - [x] não esta perto de outros geradores de features que usam datetime
  - [x] create_day_of_week=True não funciona
  - [x] não retorna dataframe indicando fds se inplace=False
  - [x] executar mais de uma vez levanta erro 
    ```python
    AttributeError: 'DataFrame' object has no attribute 'delete'
    ```

- [x] plot_all_features, plot_trajs, plot_traj_id => padronizar parâmetros e retorno

- [x] plot_traj_id =>  
    ```python
    IndexError: single positional indexer is out-of-bounds
    ```

- [x] any => não existe all

- [x] isin => existem dois métodos isin

- [x] to_csv => não possui parametro index

- [x] last_operation =>
  - [x] às vezes não exibe a última exibindo {'name': 'dtypes', 'time': 0, 'mem': 0}
  - [x] exibir valores de tempo e memoria de forma mais legível

- [x] impedir que os métodos que modifiquem as colunas removam as colunas necessárias ao MoveDataFrame => dropna, drop, set_index, astype

- [x] write_file => não esta perto de to_csv

- [x] len => não esta perto de shape

- [x] nomes de colunas com `'` e `"`

**Comment by hernanytec** [comment]
# last_operation
----
Em alguns casos a função devolve um resultado diferente do esperado:

![last_operation#26](https://user-images.githubusercontent.com/31345577/78266802-a4849180-74dc-11ea-8883-b457774f1c7e.png)

Esse tipo de problema ocorre geralmente na primeira execução.

Não encontrei erros no código que justifiquem esse comportamento. Vi que o problema se dá porque algumas funções como `dtypes`, `index` e `iloc` são chamadas **automaticamente** no próprio jupyter (e também no terminal), quando o dataframe é exibido em uma nova célula. E mesmo pra essas chamadas automáticas o valor de `last_operation` é atualizado.

## Como resolver o problema?
- Deixando de setar atributos de `last_operation` para funções da api do pandas
  - Resolve, mas não sei se seria o ideal

Outra forma? Qual?
Tem como identificar se a função foi chamada automaticamente ou de forma manual pelo usuário?

**Comment by CHSevero** [comment]
impedir que os métodos que modifiquem as colunas removam as colunas necessárias ao MoveDataFrame => dropna, drop, set_index, astype. 
Concluido.
